### ISSUE TITLE
Test meeting with reminder and location in mobile app , web and sync 

### ISSUE THREAD

**Issue by ehsmohammadi** [ehsmohammadi/BTE.RMS#24]
- [x] Reminder on MVC
- [x] Reminder mobile in sync

**Comment by ehsmohammadi** [comment]
Reminder on web tested

**Comment by mahdinai** [comment]
Reminder on mobile tested and fixed

**Comment by seifm26** [comment]
Reminder on web is ok

**Comment by ehsmohammadi** [comment]
@mahdinai  sync by action create is resolved and debugged continue your flow
