### ISSUE TITLE
Problem with Castle Windsor

### ISSUE THREAD

**Issue by pexpert28** [ehsmohammadi/BTE.RMS#36]
When I click on plus icon in first menu , I get this error "can't create component in castle windsor" while getting instance of AppointmentVM via ServiceLocator . What is the problem ?

**Comment by ehsmohammadi** [comment]
@pexpert28  send me your inner exception to tell you what you missed ,
paye attention : this problem may cause create instance from unregistered component

**Comment by ehsmohammadi** [comment]
pull the project if you dont know how to push and pull please ask your colleague @mahdinai @seifm26 
then send me the exact exception for helping you

**Comment by pexpert28** [comment]
When you start wpf project , At first when you are in main menu , click on plus icon at the bottom of the page , then error will appear. What does it mean ?

**Comment by ehsmohammadi** [comment]
As i said in first comment it was raised when you have component in your constructor that was not register in IOC 
in this case PuyaMenu and Menu page
