### ISSUE TITLE
404 error in meetingReport url when get report , like Count Report

### ISSUE THREAD

**Issue by mahdinai** [ehsmohammadi/BTE.RMS#47]

**Comment by ehsmohammadi** [comment]
this sample is for getting report count : 
URL : http://localhost:9461/api/Reports/Meetings/Counts
request content after converting to json :
{
  "MeetingType": null,
  "From":null,
  "To": null,
  "State": null,
  "WithMinuts": false,
  "WithAttachment": false
}
