### ISSUE TITLE
error call webservice Meetings Daily

### ISSUE THREAD

**Issue by seifm26** [ehsmohammadi/BTE.RMS#50]
baraye address http://localhost:9461/api/Reports/Meetings/Daily
json
{
"MeetingType": 1,
"From":null,
"To": null,
"State": null,
"WithMinuts": false,
"WithAttachment": false
}
miferestam ama error mide
{
  "Message": "\r\n\r\nMapping types:\r\nWorkingMeeting -> MeetingStateEnum\r\nBTE.RMS.Model.Meetings.WorkingMeeting -> BTE.RMS.Common.MeetingStateEnum\r\n\r\nDestination path:\r\nMeetingWithDateDto.Meetings.Meetings.Meetings0[0].State0[0].State0[0]\r\n\r\nSource value:\r\nBTE.RMS.Model.Meetings.WorkingMeeting"
}
toye classe "Enumeration" methode "parse" meghdare  matchingItem null hast

**Comment by ehsmohammadi** [comment]
I check it and when it solved will notify you ..

**Comment by ehsmohammadi** [comment]
use it in your application then call if its wring there is no problem ..
